spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/INIT
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver

users:
  process-name: USER-ACCOUNT
  info:
    name: sayya
    age: 29