spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/INIT
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver

########################################################
### Property ###########################################
########################################################
base-url: /app/wow
users:
  save-url: ${base}/upload
  process-name: USER-ACCOUNT
  info:
    name: sayya
    age: 29