server:
  port: 8008
  servlet:
    context-path: /
spring:
  application:
    name: init-application
  profiles:
    active: local
  main:
    banner-mode: log

########################################################################
### Actuator ###########################################################
########################################################################
management:
  server:
    port: ${server.port}
  endpoints:
    web:
      base-path: "/84540e75e1f132b1fe590d5de7cdcd604f01f4ed/actuator"
      exposure:
        include: "*"
    access:
      default: unrestricted
  endpoint:
    health:
      access: unrestricted
      show-details: always
    metrics:
      access: unrestricted