server:
  port: 8008
  servlet:
    context-path: /
spring:
  application:
    name: init-application
  profiles:
    active: local
  main:
    banner-mode: log

########################################################################
### Actuator ###########################################################
########################################################################
management:
  server:
    port: {port.number}  # Actuator 엔드포인트 접근 시 사용하는 서버 포트 지정
  endpoints:
    web:
      base-path: "/84540e75e1f132b1fe590d5de7cdcd604f01f4ed/actuator"  # Actuator 엔드포인트 기본 경로 지정
      exposure:
        include: prometheus, health, metrics  # 노출하고자 하는 Actuator 엔드포인트
    enabled-by-default: true
  endpoint: # 엔드포인트별 개별 설정 지정
    health:
      enabled: true
      show-details: always
    metrics:
      enabled: true